// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: health-check.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "health_check.v1";

/** HealthCheckResponse represents the health status response. */
export interface HealthCheckResponse {
  serving: boolean;
  message: string;
}

/** DependencyHealth represents the health status of a single dependency. */
export interface DependencyHealth {
  name: string;
  healthy: boolean;
  message: string;
  latencyMs: number;
}

/** ReadinessResponse represents the readiness status with per-dependency details. */
export interface ReadinessResponse {
  serving: boolean;
  message: string;
  dependencies: DependencyHealth[];
}

export const HEALTH_CHECK_V1_PACKAGE_NAME = "health_check.v1";

/** HealthCheckService defines the gRPC service for health checking. */

export interface HealthCheckServiceClient {
  /** rpc to check the health status of the service */

  checkAppHealth(request: Empty): Observable<HealthCheckResponse>;

  /** rpc to check readiness of all dependencies */

  checkAppConnections(request: Empty): Observable<ReadinessResponse>;
}

/** HealthCheckService defines the gRPC service for health checking. */

export interface HealthCheckServiceController {
  /** rpc to check the health status of the service */

  checkAppHealth(request: Empty): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  /** rpc to check readiness of all dependencies */

  checkAppConnections(request: Empty): Promise<ReadinessResponse> | Observable<ReadinessResponse> | ReadinessResponse;
}

export function HealthCheckServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAppHealth", "checkAppConnections"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("HealthCheckService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("HealthCheckService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const HEALTH_CHECK_SERVICE_NAME = "HealthCheckService";
