// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: store-category.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Language as Language1 } from "./store-item";

export const protobufPackage = "store_category.v1";

/** declaration of Language message */
export interface Language {
  language: Language1;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

/** Message representing a list of store categories */
export interface StoreCategoryList {
  data: StoreCategoryWithTranslation[];
}

/** Message representing a store category */
export interface StoreCategory {
  id: string;
  slug: string;
  isAvailable: boolean;
  sortOrder: number;
}

/** Message representing a store category with translation */
export interface StoreCategoryWithTranslation {
  id: string;
  slug: string;
  isAvailable: boolean;
  sortOrder: number;
  title: string;
  description: string;
}

/** Message representing a store category translation */
export interface StoreCategoryTranslation {
  id: string;
  title: string;
  description: string;
  language: Language1;
}

/** Message representing a store category with its translation */
export interface StoreCategoryWithTranslations {
  category: StoreCategory | null;
  translation: StoreCategoryTranslation[];
}

/** Message for creating a new store category */
export interface CreateStoreCategoryRequest {
  slug: string;
  isAvailable?: boolean | null | undefined;
  sortOrder?: number | null | undefined;
}

/** Message for updating an existing store category */
export interface UpdateStoreCategoryRequest {
  id: string;
  slug?: string | null | undefined;
  isAvailable?: boolean | null | undefined;
}

/** Message for changing the position of a store category */
export interface ChangeStoreCategoryPositionRequest {
  id: string;
  sortOrder: number;
}

/** Message for creating or updating a store category translation */
export interface StoreCategoryTranslationRequest {
  categoryId: string;
  title: string;
  description?: string | null | undefined;
  language: Language1;
}

export const STORE_CATEGORY_V1_PACKAGE_NAME = "store_category.v1";

/** StoreCategoryService defines the gRPC service for managing store categories. */

export interface StoreCategoryServiceClient {
  /** rpc to get store categories by language */

  getStoreCategoriesByLanguage(request: Language): Observable<StoreCategoryList>;

  /** rpc to get a store category by its ID */

  getStoreCategoryById(request: Id): Observable<StoreCategoryWithTranslations>;

  /** rpc to create a new store category */

  createStoreCategory(request: CreateStoreCategoryRequest): Observable<Id>;

  /** rpc to update an existing store category */

  updateStoreCategory(request: UpdateStoreCategoryRequest): Observable<Id>;

  /** rpc to delete a store category by its ID */

  deleteStoreCategory(request: Id): Observable<StatusResponse>;

  /** rpc to change the position of a store category */

  changeStoreCategoryPosition(request: ChangeStoreCategoryPositionRequest): Observable<StoreCategory>;

  /** rpc to create or update a store category translation */

  upsertStoreCategoryTranslation(request: StoreCategoryTranslationRequest): Observable<Id>;

  /** rpc to delete a store category translation by its ID */

  deleteStoreCategoryTranslation(request: Id): Observable<StatusResponse>;
}

/** StoreCategoryService defines the gRPC service for managing store categories. */

export interface StoreCategoryServiceController {
  /** rpc to get store categories by language */

  getStoreCategoriesByLanguage(
    request: Language,
  ): Promise<StoreCategoryList> | Observable<StoreCategoryList> | StoreCategoryList;

  /** rpc to get a store category by its ID */

  getStoreCategoryById(
    request: Id,
  ): Promise<StoreCategoryWithTranslations> | Observable<StoreCategoryWithTranslations> | StoreCategoryWithTranslations;

  /** rpc to create a new store category */

  createStoreCategory(request: CreateStoreCategoryRequest): Promise<Id> | Observable<Id> | Id;

  /** rpc to update an existing store category */

  updateStoreCategory(request: UpdateStoreCategoryRequest): Promise<Id> | Observable<Id> | Id;

  /** rpc to delete a store category by its ID */

  deleteStoreCategory(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to change the position of a store category */

  changeStoreCategoryPosition(
    request: ChangeStoreCategoryPositionRequest,
  ): Promise<StoreCategory> | Observable<StoreCategory> | StoreCategory;

  /** rpc to create or update a store category translation */

  upsertStoreCategoryTranslation(request: StoreCategoryTranslationRequest): Promise<Id> | Observable<Id> | Id;

  /** rpc to delete a store category translation by its ID */

  deleteStoreCategoryTranslation(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function StoreCategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getStoreCategoriesByLanguage",
      "getStoreCategoryById",
      "createStoreCategory",
      "updateStoreCategory",
      "deleteStoreCategory",
      "changeStoreCategoryPosition",
      "upsertStoreCategoryTranslation",
      "deleteStoreCategoryTranslation",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StoreCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StoreCategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STORE_CATEGORY_SERVICE_NAME = "StoreCategoryService";
